### ISSUE TITLE
wont find the serial port

### ISSUE THREAD

**Issue by Amtech7** [esphome/esphome-flasher#11]
Not sure if this is just an issue with my quite yet. I've been trying to troubleshoot, new chord, driver. but wanted to check if anyone was having the issue here.

**Comment by mcpacific** [comment]
I have the same issue. I tried a different Micro USB cord and same result.

**Comment by OttoWinter** [comment]
ESPHome-Flasher displays exactly what the operating system sees.

So the only reason the serial port is not detected would be because the OS does not find it.

There may be many reasons for this, including not having the drivers, wrong cables etc. But that's an issue of the OS, not esphome-flasher.

If you do find a solution, please post it here so that it could potentially be added to the docs.
