### ISSUE TITLE
Virus scan is coming back with infections

### ISSUE THREAD

**Issue by jchambers2012** [esphome/esphome-flasher#3]
My work slap me on the wrist because the esphomeflasher-1.0.1-windows-x64.exe came back unclean, just wanted to bring this to you attention in case the tool chain that build the exe was compromised.

https://www.virustotal.com/#/file/70fae2d2d32d95f40117c66da94e188bab8d91697956f7cfb8a19e387cd9dc65/detection

**Comment by OttoWinter** [comment]
That is very likely a false-positive. Maybe the scanner doesn't like applications packaging python.

The machine that created the binary was a fresh Windows VM (on VirtualBox) with an ISO directly downloaded from microsoft. The packager was pyinstaller (which is also used by many other projects, even many commercial ones), so also unlikely.

I will close this issue since virustotal also shows the binary as not being infected.
